# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      #ddl-auto: create-drop
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/sf53_2015
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
